### PR TITLE
Adding DuckDuckGo to the list of browsers

### PR DESCRIPTION
**Pull request by OddMagnet**
Started switching away from google, wanted to use DDG on my phone as well, found your tweak and since I already figured out the bundle id and scheme I thought I'd open a quick pull request :)

### CODE REVIEW

**Review by LorenzoPane — CHANGES_REQUESTED** [review]
Thank for your contribution.  I see that this is your first pull request on this account, so heres some advice.  First of all, please test your code before submitting a PR; you're missing a colon in `BDDefaultBrowser.m`.  Also please try to keep formatting consistent with the project you are contributing to, this can apply to comment types, curly bracket placement, or in this case indentation.  It may not be what you use personally, but it is good practice to conform to they style of the maintainer to make it more readable.  In this case use tabs rather than spaces, as that is how they are already set up.

**Comment by OddMagnet** [comment]
Thanks for the advice. I added the colon and the indentation (which took me way too long to notice why my changes didn't work like I thought they would)

**Comment by LorenzoPane** [comment]
Still using spaces on line 19 of `BDDefaultBrowser.m`.

**Comment by OddMagnet** [comment]
Interesting, apparently the default in XCode is to prefer using spaces and even if I press tab it gets replaced with 4 spaces, didn't realize that until I enabled "Show Invisibles" and looked up the "Text Editing/Indentention" setting.

should be fixed now

**Review by LorenzoPane — APPROVED** [review]

**Comment by LorenzoPane** [comment]
Looks good.  I’ll merge this when I get home.  Thanks again :)

**Pull request merged**
